# tableName,public.spsource

# spec_code,bpchar(5),NULL,可能为空
# variation_no,int4,NULL,可能为空
# mill,int4,NULL,可能为空
# type,bpchar(2),NULL,可能为空
# sub_type,bpchar(3),NULL,可能为空
# thick_from,int4,NULL,可能为空
# thick_to,int4,NULL,可能为空
# dim1,int4,NULL,可能为空
# dim2,int4,NULL,可能为空
# level,bpchar(2),NULL,可能为空
# priority,bpchar(2),NULL,可能为空
# injection,bpchar(2),NULL,可能为空
# pouring_practice,bpchar(2),NULL,可能为空
# shrouding,bpchar(2),NULL,可能为空
# slow_cooling,int4,NULL,可能为空
# hot_connecting,bpchar(1),NULL,可能为空
# sc_code,bpchar(2),NULL,可能为空
# sc_temp_min,int4,NULL,可能为空
# sc_temp_max,int4,NULL,可能为空
# sc_code_2,bpchar(2),NULL,可能为空
# sc_temp_min_2,int4,NULL,可能为空
# sc_temp_max_2,int4,NULL,可能为空
# sl_practice,bpchar(2),NULL,可能为空
# sl_temp_min,int4,NULL,可能为空
# sl_temp_max,int4,NULL,可能为空
# sl_beard,bpchar(1),NULL,可能为空
# sd_practice,bpchar(2),NULL,可能为空
# sd_temp_min,int4,NULL,可能为空
# sd_temp_max,int4,NULL,可能为空
# inspection,bpchar(2),NOT NULL,不允许为空
# sulphur_printing,bpchar(2),NULL,可能为空
# qual_code,bpchar(4),NULL,可能为空
# location,bpchar(1),NULL,可能为空
# routing_input,bpchar(1),NULL,可能为空
# use_quality_1,bpchar(4),NULL,可能为空
# use_quality_2,bpchar(4),NULL,可能为空
# use_quality_3,bpchar(4),NULL,可能为空
# use_quality_4,bpchar(4),NULL,可能为空
# use_quality_5,bpchar(4),NULL,可能为空
# use_quality_6,bpchar(4),NULL,可能为空
# use_quality_7,bpchar(4),NULL,可能为空
# steel_type,bpchar(1),NULL,可能为空
# filler_1,bpchar(5),NULL,可能为空
# teeming,bpchar(2),NULL,可能为空
# filler,bpchar(31),NULL,可能为空